version: '3.1'

services:

  cafenaveia_wordpress:
    container_name: cafenaveia_web
    image: wordpress:5.4.1-php7.4-apache
    ports:
      - 7014:80
    environment:
      WORDPRESS_DB_HOST: cafenaveia_database
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'mysql'
      WORDPRESS_DB_NAME: 'cafenaveia_db'
    links:
      - cafenaveia_database
    depends_on:
      - cafenaveia_database
    volumes:
      - cafenaveia_wordpress:/var/www/html

  cafenaveia_database:
    container_name: cafenaveia_db
    image: mysql:5.7
    ports:
     - 7015:3306
    environment:
      MYSQL_DATABASE: 'cafenaveia_db'
      MYSQL_ROOT_PASSWORD: 'mysql'
    volumes:
      - cafenaveia_database:/var/lib/mysql

volumes:
  cafenaveia_wordpress:
  cafenaveia_database:
