version: '3.1'

services:

  poupancahoje_wordpress:
    container_name: poupancahoje_web
    image: wordpress:5.4.1-php7.4-apache
    ports:
      - 7016:80
    environment:
      WORDPRESS_DB_HOST: poupancahoje_database
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'mysql'
      WORDPRESS_DB_NAME: 'poupancahoje_db'
    links:
      - poupancahoje_database
    depends_on:
      - poupancahoje_database
    volumes:
      - poupancahoje_wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  poupancahoje_database:
    container_name: poupancahoje_db
    image: mysql:5.7
    ports:
     - 7017:3306
    environment:
      MYSQL_DATABASE: 'poupancahoje_db'
      MYSQL_ROOT_PASSWORD: 'mysql'
    volumes:
      - poupancahoje_database:/var/lib/mysql

volumes:
  poupancahoje_wordpress:
  poupancahoje_database:
