version: '3.1'

services:

  ultimate_wordpress:
    container_name: ultimatehealth_web
    image: wordpress:5.4.1-php7.4-apache
    ports:
      - 7012:80
    environment:
      WORDPRESS_DB_HOST: ultimate_database
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'mysql'
      WORDPRESS_DB_NAME: 'ultimatehealth_db'
    links:
      - ultimate_database
    depends_on:
      - ultimate_database
    volumes:
      - ultimatehealth_wordpress:/var/www/html

  ultimate_database:
    container_name: ultimatehealth_db
    image: mysql:5.7
    ports:
     - 7013:3306
    environment:
      MYSQL_DATABASE: 'ultimatehealth_db'
      MYSQL_ROOT_PASSWORD: 'mysql'
    volumes:
      - ./database:/app
      - ultimatehealth_database:/var/lib/mysql

volumes:
  ultimatehealth_wordpress:
  ultimatehealth_database:
